### ISSUE TITLE
发起post请求，headers默认设置转小写的问题

### ISSUE THREAD

**Issue by yuqx1561** [easy-swoole/http-client#37]
![image](https://user-images.githubusercontent.com/51982585/158925446-27be649b-b20a-42e4-adab-60c7dde6ea17.png)
上面是默认开启的，post里没有传递对应的开关参数。
![image](https://user-images.githubusercontent.com/51982585/158925724-fca6d4c3-507a-4712-9b47-e6d391d5d4b0.png)
到这里，这个配置开关把key也转成小写了

**Comment by YiwanGi** [comment]
我也遇到了此问题 真是令人不太愉快 或许不应该默认的开启(值)转换为小写
