### ISSUE TITLE
更新1.2.6后并发请求报错

### ISSUE THREAD

**Issue by catayi** [easy-swoole/http-client#8]
1、multi的exec方法没改。
2、并发请求的情况下不能setData，post方式带参请求非常不方便，建议保留原有的setData方法，太深度封装非常不方便。

**Comment by kiss291323003** [comment]
高版本的http-client不再提供重复的Multi支持，在基础组件中，提供了 Csp并发封装。
http://easyswoole.com/cn/Components/Component/csp.html
